import { AiDetectionResult } from '../types.js';

// Common phrases generated by LLMs in code comments/docstrings
const AI_COMMENT_PATTERNS = [
  /time complexity\s*[:=]/i,
  /space complexity\s*[:=]/i,
  /base case[s]?\s*[:=]/i,
  /edge case[s]?\s*[:=]/i,
  /initialize (the |an )?(variable|result|array|pointer|map)/i,
  /iterate through (the |each )?(array|list|string|matrix|element)/i,
  /helper function to/i,
  /return the (result|final answer|computed value)/i,
  /step \d+[:.]/i,
  /optimal approach/i,
  /two[- ]pointer approach/i
];

// Typical canonical variable names heavily preferred by LLMs over rushed human contest code
const CANONICAL_AI_IDENTIFIERS = new Set([
  'currentIndex', 'leftPointer', 'rightPointer', 'frequencyMap', 'visitedNodes',
  'minHeap', 'maxHeap', 'resultList', 'currentSum', 'targetSum', 'hasCycle',
  'isValid', 'charCount', 'currentChar', 'previousNode', 'nextNode'
]);

export function detectAiGeneratedCode(candidateId: string, sourceCode: string): AiDetectionResult {
  const lines = sourceCode.split(/\r?\n/).filter((l) => l.trim().length > 0);
  const reasons: string[] = [];
  let score = 0;

  // 1. Analyze comment patterns & docstrings
  let aiCommentPatternHits = 0;
  let commentLinesCount = 0;

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith('//') || trimmed.startsWith('#') || trimmed.startsWith('*')) {
      commentLinesCount++;
      for (const pattern of AI_COMMENT_PATTERNS) {
        if (pattern.test(trimmed)) {
          aiCommentPatternHits++;
          break;
        }
      }
    }
  }

  const commentRatio = lines.length > 0 ? commentLinesCount / lines.length : 0;

  const verboseDocstrings = aiCommentPatternHits >= 2 || (commentLinesCount >= 4 && commentRatio > 0.25);
  if (verboseDocstrings) {
    score += 0.35;
    reasons.push(`Detected textbook explanatory comments or complexity annotations (${aiCommentPatternHits} AI-style markers found)`);
  }

  // 2. Check for canonical AI naming patterns
  const tokens = sourceCode.match(/[a-zA-Z_$][a-zA-Z0-9_$]*/g) || [];
  let canonicalHits = 0;
  for (const token of tokens) {
    if (CANONICAL_AI_IDENTIFIERS.has(token)) {
      canonicalHits++;
    }
  }

  const canonicalNamingPattern = canonicalHits >= 2;
  if (canonicalNamingPattern) {
    score += 0.25;
    reasons.push(`High density of formal canonical identifiers (${canonicalHits} standard textbook variable names)`);
  }

  // 3. Comment density uniformity
  const uniformCommentDensity = commentRatio >= 0.20 && commentRatio <= 0.50;
  if (uniformCommentDensity && commentLinesCount >= 3) {
    score += 0.15;
    reasons.push('Uniform, disciplined comment density typical of LLM generation');
  }

  // 4. Low-entropy formatting (AI outputs pristine spacing and structure)
  const indents = lines
    .filter((l) => l.startsWith('  ') || l.startsWith('\t'))
    .map((l) => l.match(/^(\s+)/)?.[1]?.length || 0);
  
  // If indents are multiples of 2 or 4 consistently
  const consistentIndents = indents.length > 4 && indents.every((n) => n % 2 === 0 || n % 4 === 0);
  const lowEntropyFormatting = consistentIndents;
  if (lowEntropyFormatting && lines.length > 15) {
    score += 0.10;
  }

  // 5. Standard AI boilerplate markers
  const boilerplateMatches = AI_COMMENT_PATTERNS.filter((p) => p.test(sourceCode)).length;
  const standardAiBoilerplate = boilerplateMatches >= 3;
  if (standardAiBoilerplate) {
    score += 0.20;
    reasons.push('Multiple structured section headers (Base case, Loop invariant, Complexity)');
  }

  // Cap probability between 0.0 and 0.99
  const aiProbability = Math.min(0.99, Math.max(0.05, Math.round(score * 100) / 100));

  let verdict: 'HUMAN_LIKELY' | 'SUSPICIOUS' | 'AI_GENERATED_LIKELY' = 'HUMAN_LIKELY';
  if (aiProbability >= 0.70) {
    verdict = 'AI_GENERATED_LIKELY';
  } else if (aiProbability >= 0.45) {
    verdict = 'SUSPICIOUS';
  }

  if (reasons.length === 0) {
    reasons.push('Idiosyncratic formatting and naming consistent with human-written code');
  }

  return {
    candidateId,
    aiProbability,
    reasons,
    heuristicIndicators: {
      verboseDocstrings,
      uniformCommentDensity,
      canonicalNamingPattern,
      lowEntropyFormatting,
      standardAiBoilerplate,
    },
    verdict,
  };
}
